framework:
    default_locale: fr
    enabled_locales: ['en', 'fr', 'es']
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr
#        providers: