services:
    mariadb:
          image: mariadb:10.6
          # latin1 is alias of iso-8859-1
          command: ['--character-set-server=latin1', '--collation-server=latin1_swedish_ci', '--default-authentication-plugin=mysql_native_password', '--lower_case_table_names=2']
          environment:
              MYSQL_DATABASE: default
              MYSQL_ALLOW_EMPTY_PASSWORD: 1
              MYSQL_LOWER_CASE_TABLE_NAMES: 2
          volumes:
              - ./mysql/data:/var/lib/mysql
              - .docker/my.cnf:/etc/mysql/conf.d/my.cnf
          ports:
              - ${DOCKER_MYSQL_PORT}:3306

    php:
          build:
                context: ./
                dockerfile: Dockerfile
                target: app_php_local
                args:
                    USER_ID: ${USER_ID}
                    GROUP_ID: ${GROUP_ID}
                    USER_NAME: ${USER_NAME}
                    GIT_FULLNAME: ${GIT_FULLNAME}
                    GIT_EMAIL: ${GIT_EMAIL}
          environment:
              # APP_ENV: dev
            USER_ID: ${USER_ID}
            GROUP_ID: ${GROUP_ID}
            USER_NAME: ${USER_NAME}
          volumes:
            - type: bind
              source: ${PWD}
              target: /srv/app
          ports:
              - ${DOCKER_HTTP_PORT}:8000

networks:
    develop-ehw:
    devel:
        name: devel
