initial:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'api_viewer'
api:
    resource: ./routes-generated.yaml
    prefix: /api/Food